---
title: "Reproducible Research: Peer Assessment 1"
html_document:
    keep_md: true
---


## Loading and preprocessing the data

## The first step is to read data from the downloaded csv file. The file is already downloaded, decompressed and copied into the working directory. So, it is sufficient to read the file into a local data frame.

df<-read.csv("activity.csv")
df2<-df
## Looking at the data and their class:

names(df)
## [1] "steps"    "date"     "interval"
str(df)
## 'data.frame':    17568 obs. of  3 variables:
##  $ steps   : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ date    : Factor w/ 61 levels "2012-10-01","2012-10-02",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...
## As “date” is presented as a ‘Factor’ variable, I first converted it to a variable of “Date” class.

df$date<-as.Date(df$date)




## What is mean total number of steps taken per day?

##In this data frame, there are 17568 observations over 61 days period of the study. We should first calculate the total number of steps on each day, so, I used a ‘tapply’ function.

##TotalDailySteps<-with(df, tapply(steps, date, sum, na.rm=TRUE))
##Now, I can make the histogram of total steps taken each day. As this is a simple histogram, ‘base plotting system’ is sufficient.

hist(TotalDailySteps, col = "blue")

##The next step is to report the mean and median of total number of steps taken each day. This is a simple and straight forward task! (It is nicer to set echo=FALE; however, per course instructions, I did not)

meanStep<-round(mean(TotalDailySteps), 2)
medianStep<-round(median(TotalDailySteps), 2)
##So, the mean total daily steps is 9354.23 and the median is 1.039510^{4}.


## What is the average daily activity pattern?

##For this part of analysis, we should calculate average steps taken on each 15 minutes interval across all study period. Hence, I calculated it into a new variable.

intervalSteps<-with(df, tapply(steps, interval, mean, na.rm=TRUE))
##Now, we can plot the mean step value for each interval. Again, ‘base plotting system’ is more the sufficient for this step.

plot(intervalSteps,axes = F, type="l", col="blue", xlab="Time", ylab="Average Number of Steps", main="Average Daily Activity Pattern")
axis(1,at=c(0, 36, 72, 108, 144, 180, 216, 252, 288), label = c("0:00", "3:00","6:00", "9:00", "12:00","15:00","18:00","21:00","24:00"))
axis(2)


##We also have been asked about the interval with maximum average steps taken within. We can calculate it as follow:

intervalSteps[which.max(intervalSteps)]
##      835 
## 206.1698
##I can report this in a more readable and understandable format by calculating the time period and reporting the maximum value:

MaxStepID<-which.max(intervalSteps)
Hour<-MaxStepID[[1]]%/%12
IntervalMinuteEnd<-(MaxStepID[[1]]%/%12)*5
IntervalMinuteStart<-IntervalMinuteEnd - 5
maxStep<-intervalSteps[MaxStepID]
##In this cohort, the highest average steps were taken between 8:35 and 8:40 and had a maximum value of 206.1698113.

## Imputing missing values

##First, I want to report the number of missing values.

NAcount<-sum(is.na(df$steps))
NAcount
## [1] 2304
##In this data frame, there are 2304 rows with missing value for ‘Steps’ variable.

##For imputing missing values, I use the very nice “MICE” package.

library(mice)
imputedValues<-mice(df2)
## 
##  iter imp variable
##   1   1  steps
##   1   2  steps
##   1   3  steps
##   1   4  steps
##   1   5  steps
##   2   1  steps
##   2   2  steps
##   2   3  steps
##   2   4  steps
##   2   5  steps
##   3   1  steps
##   3   2  steps
##   3   3  steps
##   3   4  steps
##   3   5  steps
##   4   1  steps
##   4   2  steps
##   4   3  steps
##   4   4  steps
##   4   5  steps
##   5   1  steps
##   5   2  steps
##   5   3  steps
##   5   4  steps
##   5   5  steps
##Now we have imputed values and can reconstruct the new database:

imputedDF<-complete(imputedValues)
##Preprocessing of new dataframe:

imputedDF$date<-as.Date(imputedDF$date)
##Now, we can use the same code as used in the first part of this assignment to produce the histogram and calculate the mean and median.

##Calculating total daily steps:
TotalDailySteps_IDF<-with(imputedDF, tapply(steps, date, sum, na.rm=TRUE))
##Making the histograms:
hist(TotalDailySteps_IDF, col = "bisque")


##Calculating the central values:
meanStep_IDF<-round(mean(TotalDailySteps_IDF), 2)
medianStep_IDF<-round(median(TotalDailySteps_IDF), 2)
##So, after imputation of the missing values, the mean total daily steps is 1.12552610^{4} and the median is 1.127910^{4}.

##Calculating the resulted change in central values:
meanDiff<- meanStep - meanStep_IDF
medianDiff<-medianStep - medianStep_IDF
##After imputation, change inmean value is -1901.03 and change in median value is -884.

## Are there differences in activity patterns between weekdays and weekends?
##In the last step, we want to compare the difference between activity on weekdays and weekends. First, I defined a variable containing the name of each week day and then defined a second variable separating weekends.

imputedDF$weekdays<-weekdays(imputedDF$date)
imputedDF$dayType<-ifelse(imputedDF$weekdays%in%c("Saturday", "Sunday"), "Weekend", "Weekday")
##Now, we can calculate average steps in each interval based on type of weekday:

intervalDaySteps<-aggregate(steps~interval+dayType, data = imputedDF, mean)
##For plotting data in two panels, I use the ggplot2 system:

library(ggplot2)
g1<-ggplot(intervalDaySteps, aes(interval, steps))
g1 + geom_line() +
        facet_grid(dayType ~ .) +
        xlab("5-minute interval") + 
        ylab("Number of steps")
